# Form implementation generated from reading ui file 'alertOk.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class alertMessage(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(434, 232)
        font = QtGui.QFont()
        font.setFamily("Cloud Light")
        font.setPointSize(12)
        Dialog.setFont(font)
        Dialog.setAutoFillBackground(False)
        Dialog.setStyleSheet("background-color: rgb(27, 29, 35);")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(70, 50, 311, 51))
        font = QtGui.QFont()
        font.setFamily("Cloud Light")
        font.setPointSize(26)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"    Color: #FFF\n"
"}")
        self.label.setObjectName("label")
        #self.cancelButton = QtWidgets.QPushButton(Dialog)
        #self.cancelButton.setGeometry(QtCore.QRect(160, 160, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Cloud Light")
        font.setPointSize(18)
        #self.cancelButton.setFont(font)
        #self.cancelButton.setStyleSheet("QPushButton {\n"
#"    border: 2px solid rgb(37,39,48);\n"
#"    border-radius: 20px;\n"
#"    color: #FFF;\n"
##"    padding-left: 20px;\n"
#"    padding-right: 20px;\n"
#"}\n"
#"QPushButton:hover {\n"
#"    border: 2px solid rgb(48, 50, 62);\n"
##"}\n"
##"QPushButton:hover:pressed\n"
#"{\n"
#"  border: 2px solid rgb(255, 73, 73);\n"
#"}")
        #self.cancelButton.setObjectName("cancelButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "เพิ่มรายการหนังสือสำเร็จ"))
        #self.cancelButton.setText(_translate("Dialog", "OK"))
        #self.cancelButton.clicked.connect(self.cancel)

    def cancel(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = alertMessage()
        self.ui.setupUi(self.window)
        self.window.close()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = alertMessage()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
